#!/usr/bin/python3
from sys import argv

def is_prime(num):
    return num > 1 and all(num % i != 0 for i in range(2, int(num**0.5) + 1))

def find_prime_factors(num):
    for i in range(2, num + 1):
        if is_prime(i) and num % i == 0:
            factor = num // i
            if is_prime(factor):
                return f"{num}={factor}*{i}"
                
if __name__ == "__main__":
    with open(argv[1]) as f:
        for line in f:
            num = int(line)
            result = find_prime_factors(num)
            if result:
                print(result)
